# Generated by Django 6.0.3 on 2026-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('speciality', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('adress', models.CharField(max_length=128)),
                ('is_actif', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=128)),
            ],
        ),
    ]
